#通用配置
spring:
  config:

  profiles:
    # 启动哪个环境
    active: @spring.profile.active@
  application:
    # 项目名称
    name: study-java
#  mvc:
#    async:
#      request-timeout: @spring.mvc.async.request.timeout@  # 设置 Spring MVC 请求超时时间为 5 分钟

server:
  # 端口
  port: @server.port@
  address: 0.0.0.0
  servlet:
    # 接口前缀
    context-path: @server.servlet.context.path@

#deepseek 配置
deepseek:
  api:
    key: ${DEEPSEEK_API_KEY:your-api-key-here}
    base-url: ${DEEPSEEK_BASE_URL:https://api.deepseek.com}



